# Generated by Django 5.0.6 on 2024-06-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_tag_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
